[workspace]
publish = false
release_always = false
semver_check = false
pr_labels = ["release"]

[[package]]
name = "qrllib"
version_group = "workspace"
publish = true

[[package]]
name = "qrllib-wasm"
version_group = "workspace"
